spring:
  application:
    name: CALLDEMO
  redis:
    host: localhost
    port: 6379
    timeout: 3000
  datasource:
    #####################################以下为MYSQL配置信息#######################################
    url: jdbc:mysql://192.168.1.64:3306/klxx_hrm
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #####################################以下为DRUID配置信息#######################################
    #http://localhost:${server.port}/druid/sql.html 监控页面
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,log4j
      filter:
        stat:
          log-slow-sql: true

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.demo.calldemo: DEBUG